Maybe change idea from whether a restaurant is successful or not to 'WHETHER IT WILL CLOSE WITHIN 2 YEARS'

In [2]:
import numpy as np
import pandas as pd
import datetime as dt

from bs4 import BeautifulSoup

### Read in Restaurant Health Score Data

In [3]:
health_scores = pd.read_csv('Restaurant_Scores_-_LIVES_Standard.csv')

In [4]:
health_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54175 entries, 0 to 54174
Data columns (total 23 columns):
business_id                  54175 non-null int64
business_name                54175 non-null object
business_address             54175 non-null object
business_city                54175 non-null object
business_state               54175 non-null object
business_postal_code         52861 non-null object
business_latitude            29457 non-null float64
business_longitude           29457 non-null float64
business_location            29457 non-null object
business_phone_number        17014 non-null float64
inspection_id                54175 non-null object
inspection_date              54175 non-null object
inspection_score             39978 non-null float64
inspection_type              54175 non-null object
violation_id                 40955 non-null object
violation_description        40955 non-null object
risk_category                40955 non-null object
Neighborhoods                29422 non-null float64
Police Districts             29422 non-null float64
Supervisor Districts         29422 non-null float64
Fire Prevention Districts    29374 non-null float64
Zip Codes                    29436 non-null float64
Analysis Neighborhoods       29422 non-null float64
dtypes: float64(10), int64(1), object(12)
memory usage: 9.5+ MB

**Possibly an issue: all health scores are from 2016-2019**
 - Need to check date ranges on other data sets (home values only go through 2017)

In [5]:
set(health_scores['inspection_date'])

{'01/01/2017 12:00:00 AM',
 '01/02/2018 12:00:00 AM',
 '01/02/2019 12:00:00 AM',
 '01/03/2017 12:00:00 AM',
 '01/03/2018 12:00:00 AM',
 '01/03/2019 12:00:00 AM',
 '01/04/2017 12:00:00 AM',
 '01/04/2018 12:00:00 AM',
 '01/04/2019 12:00:00 AM',
 '01/05/2017 12:00:00 AM',
 '01/05/2018 12:00:00 AM',
 '01/06/2017 12:00:00 AM',
 '01/06/2018 12:00:00 AM',
 '01/07/2019 12:00:00 AM',
 '01/08/2018 12:00:00 AM',
 '01/08/2019 12:00:00 AM',
 '01/09/2017 12:00:00 AM',
 '01/09/2018 12:00:00 AM',
 '01/09/2019 12:00:00 AM',
 '01/10/2017 12:00:00 AM',
 '01/10/2018 12:00:00 AM',
 '01/10/2019 12:00:00 AM',
 '01/11/2017 12:00:00 AM',
 '01/11/2018 12:00:00 AM',
 '01/11/2019 12:00:00 AM',
 '01/12/2017 12:00:00 AM',
 '01/12/2018 12:00:00 AM',
 '01/13/2017 12:00:00 AM',
 '01/14/2019 12:00:00 AM',
 '01/15/2019 12:00:00 AM',
 '01/16/2018 12:00:00 AM',
 '01/16/2019 12:00:00 AM',
 '01/17/2017 12:00:00 AM',
 '01/17/2018 12:00:00 AM',
 '01/17/2019 12:00:00 AM',
 '01/18/2017 12:00:00 AM',
 '01/18/2018 12:00:00 AM',
 '01/18/2019 12:00:00 AM',
 '01/19/2017 12:00:00 AM',
 '01/19/2018 12:00:00 AM',
 '01/20/2017 12:00:00 AM',
 '01/21/2017 12:00:00 AM',
 '01/22/2018 12:00:00 AM',
 '01/22/2019 12:00:00 AM',
 '01/23/2017 12:00:00 AM',
 '01/23/2018 12:00:00 AM',
 '01/23/2019 12:00:00 AM',
 '01/24/2017 12:00:00 AM',
 '01/24/2018 12:00:00 AM',
 '01/24/2019 12:00:00 AM',
 '01/25/2017 12:00:00 AM',
 '01/25/2018 12:00:00 AM',
 '01/25/2019 12:00:00 AM',
 '01/26/2017 12:00:00 AM',
 '01/26/2018 12:00:00 AM',
 '01/27/2017 12:00:00 AM',
 '01/27/2018 12:00:00 AM',
 '01/28/2017 12:00:00 AM',
 '01/28/2019 12:00:00 AM',
 '01/29/2018 12:00:00 AM',
 '01/29/2019 12:00:00 AM',
 '01/30/2017 12:00:00 AM',
 '01/30/2018 12:00:00 AM',
 '01/30/2019 12:00:00 AM',
 '01/31/2017 12:00:00 AM',
 '01/31/2018 12:00:00 AM',
 '01/31/2019 12:00:00 AM',
 '02/01/2017 12:00:00 AM',
 '02/01/2018 12:00:00 AM',
 '02/01/2019 12:00:00 AM',
 '02/02/2017 12:00:00 AM',
 '02/02/2018 12:00:00 AM',
 '02/03/2017 12:00:00 AM',
 '02/04/2017 12:00:00 AM',
 '02/04/2019 12:00:00 AM',
 '02/05/2018 12:00:00 AM',
 '02/05/2019 12:00:00 AM',
 '02/06/2017 12:00:00 AM',
 '02/06/2018 12:00:00 AM',
 '02/06/2019 12:00:00 AM',
 '02/07/2017 12:00:00 AM',
 '02/07/2018 12:00:00 AM',
 '02/07/2019 12:00:00 AM',
 '02/08/2017 12:00:00 AM',
 '02/08/2018 12:00:00 AM',
 '02/08/2019 12:00:00 AM',
 '02/09/2017 12:00:00 AM',
 '02/09/2018 12:00:00 AM',
 '02/10/2017 12:00:00 AM',
 '02/10/2018 12:00:00 AM',
 '02/11/2017 12:00:00 AM',
 '02/11/2019 12:00:00 AM',
 '02/12/2018 12:00:00 AM',
 '02/12/2019 12:00:00 AM',
 '02/13/2017 12:00:00 AM',
 '02/13/2018 12:00:00 AM',
 '02/13/2019 12:00:00 AM',
 '02/14/2017 12:00:00 AM',
 '02/14/2018 12:00:00 AM',
 '02/14/2019 12:00:00 AM',
 '02/15/2017 12:00:00 AM',
 '02/15/2018 12:00:00 AM',
 '02/15/2019 12:00:00 AM',
 '02/16/2017 12:00:00 AM',
 '02/16/2018 12:00:00 AM',
 '02/17/2017 12:00:00 AM',
 '02/17/2018 12:00:00 AM',
 '02/18/2017 12:00:00 AM',
 '02/19/2019 12:00:00 AM',
 '02/20/2018 12:00:00 AM',
 '02/20/2019 12:00:00 AM',
 '02/21/2017 12:00:00 AM',
 '02/21/2018 12:00:00 AM',
 '02/21/2019 12:00:00 AM',
 '02/22/2017 12:00:00 AM',
 '02/22/2018 12:00:00 AM',
 '02/22/2019 12:00:00 AM',
 '02/23/2017 12:00:00 AM',
 '02/23/2018 12:00:00 AM',
 '02/23/2019 12:00:00 AM',
 '02/24/2017 12:00:00 AM',
 '02/25/2017 12:00:00 AM',
 '02/25/2019 12:00:00 AM',
 '02/26/2018 12:00:00 AM',
 '02/26/2019 12:00:00 AM',
 '02/27/2017 12:00:00 AM',
 '02/27/2018 12:00:00 AM',
 '02/27/2019 12:00:00 AM',
 '02/28/2017 12:00:00 AM',
 '02/28/2018 12:00:00 AM',
 '02/28/2019 12:00:00 AM',
 '03/01/2017 12:00:00 AM',
 '03/01/2018 12:00:00 AM',
 '03/01/2019 12:00:00 AM',
 '03/02/2017 12:00:00 AM',
 '03/02/2018 12:00:00 AM',
 '03/03/2017 12:00:00 AM',
 '03/04/2017 12:00:00 AM',
 '03/04/2019 12:00:00 AM',
 '03/05/2018 12:00:00 AM',
 '03/05/2019 12:00:00 AM',
 '03/06/2017 12:00:00 AM',
 '03/06/2018 12:00:00 AM',
 '03/06/2019 12:00:00 AM',
 '03/07/2017 12:00:00 AM',
 '03/07/2018 12:00:00 AM',
 '03/07/2019 12:00:00 AM',
 '03/08/2017 12:00:00 AM',
 '03/08/2018 12:00:00 AM',
 '03/08/2019 12:00:00 AM',
 '03/09/2017 12:00:00 AM',
 '03/09/2018 12:00:00 AM',
 '03/10/2017 12:00:00 AM',
 '03/11/2017 12:00:00 AM',
 '03/11/2019 12:00:00 AM',
 '03/12/2018 12:00:00 AM',
 '03/12/2019 12:00:00 AM',
 '03/13/2017 12:00:00 AM',
 '03/13/2018 12:00:00 AM',
 '03/13/2019 12:00:00 AM',
 '03/14/2017 12:00:00 AM',
 '03/14/2018 12:00:00 AM',
 '03/14/2019 12:00:00 AM',
 '03/15/2017 12:00:00 AM',
 '03/15/2018 12:00:00 AM',
 '03/15/2019 12:00:00 AM',
 '03/16/2017 12:00:00 AM',
 '03/16/2018 12:00:00 AM',
 '03/17/2017 12:00:00 AM',
 '03/18/2019 12:00:00 AM',
 '03/19/2018 12:00:00 AM',
 '03/19/2019 12:00:00 AM',
 '03/20/2017 12:00:00 AM',
 '03/20/2018 12:00:00 AM',
 '03/20/2019 12:00:00 AM',
 '03/21/2017 12:00:00 AM',
 '03/21/2018 12:00:00 AM',
 '03/21/2019 12:00:00 AM',
 '03/22/2017 12:00:00 AM',
 '03/22/2018 12:00:00 AM',
 '03/22/2019 12:00:00 AM',
 '03/23/2017 12:00:00 AM',
 '03/23/2018 12:00:00 AM',
 '03/24/2017 12:00:00 AM',
 '03/25/2017 12:00:00 AM',
 '03/25/2019 12:00:00 AM',
 '03/26/2017 12:00:00 AM',
 '03/26/2018 12:00:00 AM',
 '03/26/2019 12:00:00 AM',
 '03/27/2017 12:00:00 AM',
 '03/27/2018 12:00:00 AM',
 '03/27/2019 12:00:00 AM',
 '03/28/2017 12:00:00 AM',
 '03/28/2018 12:00:00 AM',
 '03/28/2019 12:00:00 AM',
 '03/29/2017 12:00:00 AM',
 '03/29/2018 12:00:00 AM',
 '03/29/2019 12:00:00 AM',
 '03/30/2017 12:00:00 AM',
 '03/30/2018 12:00:00 AM',
 '03/31/2017 12:00:00 AM',
 '04/01/2017 12:00:00 AM',
 '04/01/2019 12:00:00 AM',
 '04/02/2018 12:00:00 AM',
 '04/02/2019 12:00:00 AM',
 '04/03/2017 12:00:00 AM',
 '04/03/2018 12:00:00 AM',
 '04/03/2019 12:00:00 AM',
 '04/04/2017 12:00:00 AM',
 '04/04/2018 12:00:00 AM',
 '04/04/2019 12:00:00 AM',
 '04/05/2017 12:00:00 AM',
 '04/05/2018 12:00:00 AM',
 '04/05/2019 12:00:00 AM',
 '04/06/2017 12:00:00 AM',
 '04/06/2018 12:00:00 AM',
 '04/07/2017 12:00:00 AM',
 '04/08/2017 12:00:00 AM',
 '04/08/2019 12:00:00 AM',
 '04/09/2018 12:00:00 AM',
 '04/09/2019 12:00:00 AM',
 '04/10/2017 12:00:00 AM',
 '04/10/2018 12:00:00 AM',
 '04/10/2019 12:00:00 AM',
 '04/11/2017 12:00:00 AM',
 '04/11/2018 12:00:00 AM',
 '04/11/2019 12:00:00 AM',
 '04/12/2017 12:00:00 AM',
 '04/12/2018 12:00:00 AM',
 '04/12/2019 12:00:00 AM',
 '04/13/2017 12:00:00 AM',
 '04/13/2018 12:00:00 AM',
 '04/14/2017 12:00:00 AM',
 '04/14/2018 12:00:00 AM',
 '04/15/2017 12:00:00 AM',
 '04/15/2019 12:00:00 AM',
 '04/16/2018 12:00:00 AM',
 '04/16/2019 12:00:00 AM',
 '04/17/2017 12:00:00 AM',
 '04/17/2018 12:00:00 AM',
 '04/17/2019 12:00:00 AM',
 '04/18/2017 12:00:00 AM',
 '04/18/2018 12:00:00 AM',
 '04/18/2019 12:00:00 AM',
 '04/19/2017 12:00:00 AM',
 '04/19/2018 12:00:00 AM',
 '04/19/2019 12:00:00 AM',
 '04/20/2017 12:00:00 AM',
 '04/20/2018 12:00:00 AM',
 '04/20/2019 12:00:00 AM',
 '04/21/2017 12:00:00 AM',
 '04/22/2017 12:00:00 AM',
 '04/22/2019 12:00:00 AM',
 '04/23/2018 12:00:00 AM',
 '04/23/2019 12:00:00 AM',
 '04/24/2017 12:00:00 AM',
 '04/24/2018 12:00:00 AM',
 '04/25/2016 12:00:00 AM',
 '04/25/2017 12:00:00 AM',
 '04/25/2018 12:00:00 AM',
 '04/26/2016 12:00:00 AM',
 '04/26/2017 12:00:00 AM',
 '04/26/2018 12:00:00 AM',
 '04/26/2019 12:00:00 AM',
 '04/27/2016 12:00:00 AM',
 '04/27/2017 12:00:00 AM',
 '04/27/2018 12:00:00 AM',
 '04/27/2019 12:00:00 AM',
 '04/28/2016 12:00:00 AM',
 '04/28/2017 12:00:00 AM',
 '04/29/2016 12:00:00 AM',
 '04/29/2017 12:00:00 AM',
 '04/30/2016 12:00:00 AM',
 '04/30/2018 12:00:00 AM',
 '05/01/2017 12:00:00 AM',
 '05/01/2018 12:00:00 AM',
 '05/02/2016 12:00:00 AM',
 '05/02/2017 12:00:00 AM',
 '05/02/2018 12:00:00 AM',
 '05/03/2016 12:00:00 AM',
 '05/03/2017 12:00:00 AM',
 '05/03/2018 12:00:00 AM',
 '05/04/2016 12:00:00 AM',
 '05/04/2017 12:00:00 AM',
 '05/04/2018 12:00:00 AM',
 '05/05/2016 12:00:00 AM',
 '05/05/2017 12:00:00 AM',
 '05/06/2016 12:00:00 AM',
 '05/06/2017 12:00:00 AM',
 '05/07/2016 12:00:00 AM',
 '05/07/2017 12:00:00 AM',
 '05/07/2018 12:00:00 AM',
 '05/08/2017 12:00:00 AM',
 '05/08/2018 12:00:00 AM',
 '05/09/2016 12:00:00 AM',
 '05/09/2017 12:00:00 AM',
 '05/09/2018 12:00:00 AM',
 '05/10/2016 12:00:00 AM',
 '05/10/2017 12:00:00 AM',
 '05/10/2018 12:00:00 AM',
 '05/11/2016 12:00:00 AM',
 '05/11/2017 12:00:00 AM',
 '05/11/2018 12:00:00 AM',
 '05/12/2016 12:00:00 AM',
 '05/12/2017 12:00:00 AM',
 '05/13/2016 12:00:00 AM',
 '05/14/2016 12:00:00 AM',
 '05/14/2018 12:00:00 AM',
 '05/15/2017 12:00:00 AM',
 '05/15/2018 12:00:00 AM',
 '05/16/2016 12:00:00 AM',
 '05/16/2017 12:00:00 AM',
 '05/16/2018 12:00:00 AM',
 '05/17/2016 12:00:00 AM',
 '05/17/2017 12:00:00 AM',
 '05/17/2018 12:00:00 AM',
 '05/18/2016 12:00:00 AM',
 '05/18/2017 12:00:00 AM',
 '05/18/2018 12:00:00 AM',
 '05/19/2016 12:00:00 AM',
 '05/19/2017 12:00:00 AM',
 '05/20/2016 12:00:00 AM',
 '05/20/2017 12:00:00 AM',
 '05/21/2018 12:00:00 AM',
 '05/22/2017 12:00:00 AM',
 '05/22/2018 12:00:00 AM',
 '05/23/2016 12:00:00 AM',
 '05/23/2017 12:00:00 AM',
 '05/23/2018 12:00:00 AM',
 '05/24/2016 12:00:00 AM',
 '05/24/2017 12:00:00 AM',
 '05/24/2018 12:00:00 AM',
 '05/25/2016 12:00:00 AM',
 '05/25/2017 12:00:00 AM',
 '05/25/2018 12:00:00 AM',
 '05/26/2016 12:00:00 AM',
 '05/26/2017 12:00:00 AM',
 '05/27/2016 12:00:00 AM',
 '05/28/2016 12:00:00 AM',
 '05/29/2018 12:00:00 AM',
 '05/30/2017 12:00:00 AM',
 '05/30/2018 12:00:00 AM',
 '05/31/2016 12:00:00 AM',
 '05/31/2017 12:00:00 AM',
 '05/31/2018 12:00:00 AM',
 '06/01/2016 12:00:00 AM',
 '06/01/2017 12:00:00 AM',
 '06/01/2018 12:00:00 AM',
 '06/02/2016 12:00:00 AM',
 '06/02/2017 12:00:00 AM',
 '06/02/2018 12:00:00 AM',
 '06/03/2016 12:00:00 AM',
 '06/03/2017 12:00:00 AM',
 '06/04/2018 12:00:00 AM',
 '06/05/2017 12:00:00 AM',
 '06/05/2018 12:00:00 AM',
 '06/06/2016 12:00:00 AM',
 '06/06/2017 12:00:00 AM',
 '06/06/2018 12:00:00 AM',
 '06/07/2016 12:00:00 AM',
 '06/07/2017 12:00:00 AM',
 '06/07/2018 12:00:00 AM',
 '06/08/2016 12:00:00 AM',
 '06/08/2017 12:00:00 AM',
 '06/08/2018 12:00:00 AM',
 '06/09/2016 12:00:00 AM',
 '06/09/2017 12:00:00 AM',
 '06/09/2018 12:00:00 AM',
 '06/10/2016 12:00:00 AM',
 '06/10/2017 12:00:00 AM',
 '06/11/2016 12:00:00 AM',
 '06/11/2018 12:00:00 AM',
 '06/12/2017 12:00:00 AM',
 '06/12/2018 12:00:00 AM',
 '06/13/2016 12:00:00 AM',
 '06/13/2017 12:00:00 AM',
 '06/13/2018 12:00:00 AM',
 '06/14/2016 12:00:00 AM',
 '06/14/2017 12:00:00 AM',
 '06/14/2018 12:00:00 AM',
 '06/15/2016 12:00:00 AM',
 '06/15/2017 12:00:00 AM',
 '06/15/2018 12:00:00 AM',
 '06/16/2016 12:00:00 AM',
 '06/16/2017 12:00:00 AM',
 '06/16/2018 12:00:00 AM',
 '06/17/2016 12:00:00 AM',
 '06/17/2017 12:00:00 AM',
 '06/18/2016 12:00:00 AM',
 '06/18/2018 12:00:00 AM',
 '06/19/2017 12:00:00 AM',
 '06/19/2018 12:00:00 AM',
 '06/20/2016 12:00:00 AM',
 '06/20/2017 12:00:00 AM',
 '06/20/2018 12:00:00 AM',
 '06/21/2016 12:00:00 AM',
 '06/21/2017 12:00:00 AM',
 '06/21/2018 12:00:00 AM',
 '06/22/2016 12:00:00 AM',
 '06/22/2017 12:00:00 AM',
 '06/22/2018 12:00:00 AM',
 '06/23/2016 12:00:00 AM',
 '06/23/2017 12:00:00 AM',
 '06/24/2016 12:00:00 AM',
 '06/25/2016 12:00:00 AM',
 '06/25/2018 12:00:00 AM',
 '06/26/2017 12:00:00 AM',
 '06/26/2018 12:00:00 AM',
 '06/27/2016 12:00:00 AM',
 '06/27/2017 12:00:00 AM',
 '06/27/2018 12:00:00 AM',
 '06/28/2016 12:00:00 AM',
 '06/28/2017 12:00:00 AM',
 '06/28/2018 12:00:00 AM',
 '06/29/2016 12:00:00 AM',
 '06/29/2017 12:00:00 AM',
 '06/29/2018 12:00:00 AM',
 '06/30/2016 12:00:00 AM',
 '06/30/2017 12:00:00 AM',
 '06/30/2018 12:00:00 AM',
 '07/01/2016 12:00:00 AM',
 '07/02/2016 12:00:00 AM',
 '07/02/2018 12:00:00 AM',
 '07/03/2016 12:00:00 AM',
 '07/03/2017 12:00:00 AM',
 '07/03/2018 12:00:00 AM',
 '07/05/2016 12:00:00 AM',
 '07/05/2017 12:00:00 AM',
 '07/05/2018 12:00:00 AM',
 '07/06/2016 12:00:00 AM',
 '07/06/2017 12:00:00 AM',
 '07/06/2018 12:00:00 AM',
 '07/07/2016 12:00:00 AM',
 '07/07/2017 12:00:00 AM',
 '07/08/2016 12:00:00 AM',
 '07/08/2017 12:00:00 AM',
 '07/09/2016 12:00:00 AM',
 '07/09/2018 12:00:00 AM',
 '07/10/2016 12:00:00 AM',
 '07/10/2017 12:00:00 AM',
 '07/10/2018 12:00:00 AM',
 '07/11/2016 12:00:00 AM',
 '07/11/2017 12:00:00 AM',
 '07/11/2018 12:00:00 AM',
 '07/12/2016 12:00:00 AM',
 '07/12/2017 12:00:00 AM',
 '07/12/2018 12:00:00 AM',
 '07/13/2016 12:00:00 AM',
 '07/13/2017 12:00:00 AM',
 '07/13/2018 12:00:00 AM',
 '07/14/2016 12:00:00 AM',
 '07/14/2017 12:00:00 AM',
 '07/15/2016 12:00:00 AM',
 '07/15/2017 12:00:00 AM',
 '07/16/2018 12:00:00 AM',
 '07/17/2017 12:00:00 AM',
 '07/17/2018 12:00:00 AM',
 '07/18/2016 12:00:00 AM',
 '07/18/2017 12:00:00 AM',
 '07/18/2018 12:00:00 AM',
 '07/19/2016 12:00:00 AM',
 '07/19/2017 12:00:00 AM',
 '07/19/2018 12:00:00 AM',
 '07/20/2016 12:00:00 AM',
 '07/20/2017 12:00:00 AM',
 '07/20/2018 12:00:00 AM',
 '07/21/2016 12:00:00 AM',
 '07/21/2017 12:00:00 AM',
 '07/22/2016 12:00:00 AM',
 '07/22/2017 12:00:00 AM',
 '07/23/2018 12:00:00 AM',
 '07/24/2016 12:00:00 AM',
 '07/24/2017 12:00:00 AM',
 '07/24/2018 12:00:00 AM',
 '07/25/2016 12:00:00 AM',
 '07/25/2017 12:00:00 AM',
 '07/25/2018 12:00:00 AM',
 '07/26/2016 12:00:00 AM',
 '07/26/2017 12:00:00 AM',
 '07/26/2018 12:00:00 AM',
 '07/27/2016 12:00:00 AM',
 '07/27/2017 12:00:00 AM',
 '07/27/2018 12:00:00 AM',
 '07/28/2016 12:00:00 AM',
 '07/28/2017 12:00:00 AM',
 '07/29/2016 12:00:00 AM',
 '07/30/2016 12:00:00 AM',
 '07/30/2018 12:00:00 AM',
 '07/31/2017 12:00:00 AM',
 '07/31/2018 12:00:00 AM',
 '08/01/2016 12:00:00 AM',
 '08/01/2017 12:00:00 AM',
 '08/01/2018 12:00:00 AM',
 '08/02/2016 12:00:00 AM',
 '08/02/2017 12:00:00 AM',
 '08/02/2018 12:00:00 AM',
 '08/03/2016 12:00:00 AM',
 '08/03/2017 12:00:00 AM',
 '08/03/2018 12:00:00 AM',
 '08/04/2016 12:00:00 AM',
 '08/04/2017 12:00:00 AM',
 '08/05/2016 12:00:00 AM',
 '08/06/2016 12:00:00 AM',
 '08/06/2018 12:00:00 AM',
 '08/07/2017 12:00:00 AM',
 '08/07/2018 12:00:00 AM',
 '08/08/2016 12:00:00 AM',
 '08/08/2017 12:00:00 AM',
 '08/08/2018 12:00:00 AM',
 '08/09/2016 12:00:00 AM',
 '08/09/2017 12:00:00 AM',
 '08/09/2018 12:00:00 AM',
 '08/10/2016 12:00:00 AM',
 '08/10/2017 12:00:00 AM',
 '08/10/2018 12:00:00 AM',
 '08/11/2016 12:00:00 AM',
 '08/11/2017 12:00:00 AM',
 '08/11/2018 12:00:00 AM',
 '08/12/2016 12:00:00 AM',
 '08/13/2018 12:00:00 AM',
 '08/14/2016 12:00:00 AM',
 '08/14/2017 12:00:00 AM',
 '08/14/2018 12:00:00 AM',
 '08/15/2016 12:00:00 AM',
 '08/15/2017 12:00:00 AM',
 '08/15/2018 12:00:00 AM',
 '08/16/2016 12:00:00 AM',
 '08/16/2017 12:00:00 AM',
 '08/16/2018 12:00:00 AM',
 '08/17/2016 12:00:00 AM',
 '08/17/2017 12:00:00 AM',
 '08/17/2018 12:00:00 AM',
 '08/18/2016 12:00:00 AM',
 '08/18/2017 12:00:00 AM',
 '08/19/2016 12:00:00 AM',
 '08/19/2017 12:00:00 AM',
 '08/20/2018 12:00:00 AM',
 '08/21/2017 12:00:00 AM',
 '08/21/2018 12:00:00 AM',
 '08/22/2016 12:00:00 AM',
 '08/22/2017 12:00:00 AM',
 '08/22/2018 12:00:00 AM',
 '08/23/2016 12:00:00 AM',
 '08/23/2017 12:00:00 AM',
 '08/23/2018 12:00:00 AM',
 '08/24/2016 12:00:00 AM',
 '08/24/2017 12:00:00 AM',
 '08/24/2018 12:00:00 AM',
 '08/25/2016 12:00:00 AM',
 '08/25/2017 12:00:00 AM',
 '08/26/2016 12:00:00 AM',
 '08/26/2017 12:00:00 AM',
 '08/27/2018 12:00:00 AM',
 '08/28/2017 12:00:00 AM',
 '08/28/2018 12:00:00 AM',
 '08/29/2016 12:00:00 AM',
 '08/29/2017 12:00:00 AM',
 '08/29/2018 12:00:00 AM',
 '08/30/2016 12:00:00 AM',
 '08/30/2017 12:00:00 AM',
 '08/30/2018 12:00:00 AM',
 '08/31/2016 12:00:00 AM',
 '08/31/2017 12:00:00 AM',
 '08/31/2018 12:00:00 AM',
 '09/01/2016 12:00:00 AM',
 '09/01/2017 12:00:00 AM',
 '09/02/2016 12:00:00 AM',
 '09/02/2017 12:00:00 AM',
 '09/03/2016 12:00:00 AM',
 '09/04/2018 12:00:00 AM',
 '09/05/2017 12:00:00 AM',
 '09/05/2018 12:00:00 AM',
 '09/06/2016 12:00:00 AM',
 '09/06/2017 12:00:00 AM',
 '09/06/2018 12:00:00 AM',
 '09/07/2016 12:00:00 AM',
 '09/07/2017 12:00:00 AM',
 '09/07/2018 12:00:00 AM',
 '09/08/2016 12:00:00 AM',
 '09/08/2017 12:00:00 AM',
 '09/09/2016 12:00:00 AM',
 '09/10/2018 12:00:00 AM',
 '09/11/2017 12:00:00 AM',
 '09/11/2018 12:00:00 AM',
 '09/12/2016 12:00:00 AM',
 '09/12/2017 12:00:00 AM',
 '09/12/2018 12:00:00 AM',
 '09/13/2016 12:00:00 AM',
 '09/13/2017 12:00:00 AM',
 '09/13/2018 12:00:00 AM',
 '09/14/2016 12:00:00 AM',
 '09/14/2017 12:00:00 AM',
 '09/14/2018 12:00:00 AM',
 '09/15/2016 12:00:00 AM',
 '09/15/2017 12:00:00 AM',
 '09/16/2016 12:00:00 AM',
 '09/17/2016 12:00:00 AM',
 '09/17/2017 12:00:00 AM',
 '09/17/2018 12:00:00 AM',
 '09/18/2016 12:00:00 AM',
 '09/18/2017 12:00:00 AM',
 '09/18/2018 12:00:00 AM',
 '09/19/2016 12:00:00 AM',
 '09/19/2017 12:00:00 AM',
 '09/19/2018 12:00:00 AM',
 '09/20/2016 12:00:00 AM',
 '09/20/2017 12:00:00 AM',
 '09/20/2018 12:00:00 AM',
 '09/21/2016 12:00:00 AM',
 '09/21/2017 12:00:00 AM',
 '09/21/2018 12:00:00 AM',
 '09/22/2016 12:00:00 AM',
 '09/22/2017 12:00:00 AM',
 '09/22/2018 12:00:00 AM',
 '09/23/2016 12:00:00 AM',
 '09/23/2017 12:00:00 AM',
 '09/23/2018 12:00:00 AM',
 '09/24/2016 12:00:00 AM',
 '09/24/2018 12:00:00 AM',
 '09/25/2016 12:00:00 AM',
 '09/25/2017 12:00:00 AM',
 '09/25/2018 12:00:00 AM',
 '09/26/2016 12:00:00 AM',
 '09/26/2017 12:00:00 AM',
 '09/26/2018 12:00:00 AM',
 '09/27/2016 12:00:00 AM',
 '09/27/2017 12:00:00 AM',
 '09/27/2018 12:00:00 AM',
 '09/28/2016 12:00:00 AM',
 '09/28/2017 12:00:00 AM',
 '09/28/2018 12:00:00 AM',
 '09/29/2016 12:00:00 AM',
 '09/29/2017 12:00:00 AM',
 '09/30/2016 12:00:00 AM',
 '09/30/2017 12:00:00 AM',
 '10/01/2018 12:00:00 AM',
 '10/02/2016 12:00:00 AM',
 '10/02/2017 12:00:00 AM',
 '10/02/2018 12:00:00 AM',
 '10/03/2016 12:00:00 AM',
 '10/03/2017 12:00:00 AM',
 '10/03/2018 12:00:00 AM',
 '10/04/2016 12:00:00 AM',
 '10/04/2017 12:00:00 AM',
 '10/04/2018 12:00:00 AM',
 '10/05/2016 12:00:00 AM',
 '10/05/2017 12:00:00 AM',
 '10/05/2018 12:00:00 AM',
 '10/06/2016 12:00:00 AM',
 '10/06/2017 12:00:00 AM',
 '10/07/2016 12:00:00 AM',
 '10/08/2016 12:00:00 AM',
 '10/09/2016 12:00:00 AM',
 '10/09/2018 12:00:00 AM',
 '10/10/2017 12:00:00 AM',
 '10/10/2018 12:00:00 AM',
 '10/11/2016 12:00:00 AM',
 '10/11/2017 12:00:00 AM',
 '10/11/2018 12:00:00 AM',
 '10/12/2016 12:00:00 AM',
 '10/12/2017 12:00:00 AM',
 '10/12/2018 12:00:00 AM',
 '10/13/2016 12:00:00 AM',
 '10/13/2017 12:00:00 AM',
 '10/14/2016 12:00:00 AM',
 '10/15/2016 12:00:00 AM',
 '10/15/2018 12:00:00 AM',
 '10/16/2016 12:00:00 AM',
 '10/16/2017 12:00:00 AM',
 '10/16/2018 12:00:00 AM',
 '10/17/2016 12:00:00 AM',
 '10/17/2017 12:00:00 AM',
 '10/17/2018 12:00:00 AM',
 '10/18/2016 12:00:00 AM',
 '10/18/2017 12:00:00 AM',
 '10/18/2018 12:00:00 AM',
 '10/19/2016 12:00:00 AM',
 '10/19/2017 12:00:00 AM',
 '10/19/2018 12:00:00 AM',
 '10/20/2016 12:00:00 AM',
 '10/20/2017 12:00:00 AM',
 '10/21/2016 12:00:00 AM',
 '10/21/2017 12:00:00 AM',
 '10/22/2016 12:00:00 AM',
 '10/22/2017 12:00:00 AM',
 '10/22/2018 12:00:00 AM',
 '10/23/2017 12:00:00 AM',
 '10/23/2018 12:00:00 AM',
 '10/24/2016 12:00:00 AM',
 '10/24/2017 12:00:00 AM',
 '10/24/2018 12:00:00 AM',
 '10/25/2016 12:00:00 AM',
 '10/25/2017 12:00:00 AM',
 '10/25/2018 12:00:00 AM',
 '10/26/2016 12:00:00 AM',
 '10/26/2017 12:00:00 AM',
 '10/26/2018 12:00:00 AM',
 '10/27/2016 12:00:00 AM',
 '10/27/2017 12:00:00 AM',
 '10/27/2018 12:00:00 AM',
 '10/28/2016 12:00:00 AM',
 '10/28/2017 12:00:00 AM',
 '10/29/2016 12:00:00 AM',
 '10/29/2018 12:00:00 AM',
 '10/30/2017 12:00:00 AM',
 '10/30/2018 12:00:00 AM',
 '10/31/2016 12:00:00 AM',
 '10/31/2017 12:00:00 AM',
 '10/31/2018 12:00:00 AM',
 '11/01/2016 12:00:00 AM',
 '11/01/2017 12:00:00 AM',
 '11/01/2018 12:00:00 AM',
 '11/02/2016 12:00:00 AM',
 '11/02/2017 12:00:00 AM',
 '11/02/2018 12:00:00 AM',
 '11/03/2016 12:00:00 AM',
 '11/03/2017 12:00:00 AM',
 '11/04/2016 12:00:00 AM',
 '11/05/2018 12:00:00 AM',
 '11/06/2017 12:00:00 AM',
 '11/06/2018 12:00:00 AM',
 '11/07/2016 12:00:00 AM',
 '11/07/2017 12:00:00 AM',
 '11/07/2018 12:00:00 AM',
 '11/08/2016 12:00:00 AM',
 '11/08/2017 12:00:00 AM',
 '11/08/2018 12:00:00 AM',
 '11/09/2016 12:00:00 AM',
 '11/09/2017 12:00:00 AM',
 '11/09/2018 12:00:00 AM',
 '11/10/2016 12:00:00 AM',
 '11/10/2017 12:00:00 AM',
 '11/11/2016 12:00:00 AM',
 '11/13/2017 12:00:00 AM',
 '11/13/2018 12:00:00 AM',
 '11/14/2016 12:00:00 AM',
 '11/14/2017 12:00:00 AM',
 '11/14/2018 12:00:00 AM',
 '11/15/2017 12:00:00 AM',
 '11/15/2018 12:00:00 AM',

### Read in Business License Data

In [63]:
business_locs = pd.read_csv('Registered_Business_Locations_-_San_Francisco.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [64]:
business_locs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236905 entries, 0 to 236904
Data columns (total 36 columns):
Location Id                            236905 non-null object
Business Account Number                236905 non-null int64
Ownership Name                         236905 non-null object
DBA Name                               236905 non-null object
Street Address                         236901 non-null object
City                                   236712 non-null object
State                                  236295 non-null object
Source Zipcode                         236699 non-null float64
Business Start Date                    236904 non-null object
Business End Date                      82583 non-null object
Location Start Date                    236904 non-null object
Location End Date                      105530 non-null object
Mail Address                           154322 non-null object
Mail City                              156508 non-null object
Mail Zipcode                           156480 non-null object
Mail State                             154274 non-null object
NAICS Code                             144831 non-null object
NAICS Code Description                 144831 non-null object
Parking Tax                            236905 non-null bool
Transient Occupancy Tax                236905 non-null bool
LIC Code                               15277 non-null object
LIC Code Description                   14733 non-null object
Supervisor District                    149384 non-null float64
Neighborhoods - Analysis Boundaries    149379 non-null object
Business Corridor                      314 non-null object
Business Location                      170892 non-null object
SF Find Neighborhoods                  141868 non-null float64
Current Police Districts               141478 non-null float64
Current Supervisor Districts           141993 non-null float64
Analysis Neighborhoods                 141987 non-null float64
:@computed_region_bh8s_q3mv            167329 non-null float64
:@computed_region_yftq_j783            141493 non-null float64
:@computed_region_rxqg_mtj9            141993 non-null float64
:@computed_region_jx4q_fizf            141456 non-null float64
:@computed_region_fyvs_ahh9            141987 non-null float64
:@computed_region_p5aj_wyqh            141456 non-null float64
dtypes: bool(2), float64(12), int64(1), object(21)
memory usage: 61.9+ MB

In [65]:
set(business_locs['NAICS Code Description'])

{'Accommodations',
 'Administrative and Support Services',
 'Arts, Entertainment, and Recreation',
 'Certain Services',
 'Construction',
 'Financial Services',
 'Food Services',
 'Information',
 'Insurance',
 'Manufacturing',
 'Multiple',
 'Private Education and Health Services',
 'Professional, Scientific, and Technical Services',
 'Real Estate and Rental and Leasing Services',
 'Retail Trade',
 'Transportation and Warehousing',
 'Utilities',
 'Wholesale Trade',
 nan}

**Want to drop all business listings that are not restaurants**
 - aka keep only 'Food Services'

In [66]:
business_locs = business_locs.loc[business_locs['NAICS Code Description'] == 'Food Services']

In [67]:
business_locs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11530 entries, 61 to 236899
Data columns (total 36 columns):
Location Id                            11530 non-null object
Business Account Number                11530 non-null int64
Ownership Name                         11530 non-null object
DBA Name                               11530 non-null object
Street Address                         11530 non-null object
City                                   11530 non-null object
State                                  11529 non-null object
Source Zipcode                         11499 non-null float64
Business Start Date                    11530 non-null object
Business End Date                      2290 non-null object
Location Start Date                    11530 non-null object
Location End Date                      3845 non-null object
Mail Address                           9240 non-null object
Mail City                              9385 non-null object
Mail Zipcode                           9385 non-null object
Mail State                             9239 non-null object
NAICS Code                             11530 non-null object
NAICS Code Description                 11530 non-null object
Parking Tax                            11530 non-null bool
Transient Occupancy Tax                11530 non-null bool
LIC Code                               5530 non-null object
LIC Code Description                   5528 non-null object
Supervisor District                    6335 non-null float64
Neighborhoods - Analysis Boundaries    6335 non-null object
Business Corridor                      18 non-null object
Business Location                      7093 non-null object
SF Find Neighborhoods                  6590 non-null float64
Current Police Districts               6586 non-null float64
Current Supervisor Districts           6593 non-null float64
Analysis Neighborhoods                 6593 non-null float64
:@computed_region_bh8s_q3mv            6907 non-null float64
:@computed_region_yftq_j783            6556 non-null float64
:@computed_region_rxqg_mtj9            6593 non-null float64
:@computed_region_jx4q_fizf            6585 non-null float64
:@computed_region_fyvs_ahh9            6593 non-null float64
:@computed_region_p5aj_wyqh            6585 non-null float64
dtypes: bool(2), float64(12), int64(1), object(21)
memory usage: 3.1+ MB

In [68]:
business_locs = business_locs[['Location Id', 'Business Account Number', 
                               'DBA Name', 'Street Address', 'Source Zipcode', 
                               'Business Start Date', 'Business End Date', 
                               'Location Start Date', 'Location End Date']]

**Only keep observations with Zipcodes included**

In [69]:
business_locs = business_locs[pd.notnull(business_locs['Source Zipcode'])]

In [70]:
#Convert Zipcodes to int
business_locs['Source Zipcode'] = business_locs['Source Zipcode'].apply(lambda x: int(x))

In [71]:
business_locs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11499 entries, 61 to 236899
Data columns (total 9 columns):
Location Id                11499 non-null object
Business Account Number    11499 non-null int64
DBA Name                   11499 non-null object
Street Address             11499 non-null object
Source Zipcode             11499 non-null int64
Business Start Date        11499 non-null object
Business End Date          2286 non-null object
Location Start Date        11499 non-null object
Location End Date          3840 non-null object
dtypes: int64(2), object(7)
memory usage: 898.4+ KB

In [72]:
business_locs.head()

,Location Id,Business Account Number,DBA Name,Street Address,Source Zipcode,Business Start Date,Business End Date,Location Start Date,Location End Date
61,0000671-01-001,671,Aliotos,360 Jefferson St,94133,10/01/1968,NaN,10/01/1968,NaN
62,0000671-01-002,671,Aliotos,8 Fisherman's Wharf,94133,10/01/1968,NaN,10/01/1968,NaN
63,0000671-08-001,671,Nonna Rose Restaurant Inc,8 Fisherman's Wharf,94133,10/01/1968,NaN,04/28/2008,NaN
64,0000671-09-001,671,Afc Cafe 8 Inc,8 Fisherman's Wharf,94133,10/01/1968,NaN,04/28/2008,NaN
65,0000671-10-001,671,Afc Crabstand Inc,8 Fisherman's Wharf,94133,10/01/1968,NaN,04/28/2008,NaN

**To-do:**
 
 - add column for duration LOCATION has been open
 - add column for SUCCESSFUL LOCATION

Note: business end date vs location end date matters --> location end date means they might have just moved.  Pretty sure business end date corresponds to location closing due to going out of business, not just moving, so we'll focus on those  
 

*Exclude newly-opened businesses (those open <2 yrs)*

In [74]:
#Convert non-null Location & Business Start & End Dates to datetime objects
business_locs['Business Start Date'] = pd.to_datetime(business_locs['Business Start Date'], format='%m/%d/%Y')
business_locs['Business End Date'] = pd.to_datetime(business_locs['Business End Date'], format='%m/%d/%Y')

business_locs['Location Start Date'] = pd.to_datetime(business_locs['Location Start Date'], format='%m/%d/%Y')
business_locs['Location End Date'] = pd.to_datetime(business_locs['Location End Date'], format='%m/%d/%Y')

In [80]:
#Add column for 'Currently Open' to distinguish closed locations from open ones
business_locs.loc[business_locs['Location End Date'].isnull(), 'Currently Open'] = 1
business_locs.loc[business_locs['Location End Date'].notnull(), 'Currently Open'] = 0

In [ ]:
#Determine length of time location has been open

In [94]:
#Length of time open for closed businesses
business_locs.loc[business_locs['Location End Date'].notnull(), 'Years Open'] = ((
    business_locs['Location End Date'] - business_locs['Location Start Date']).dt.days)/365

In [95]:
#Length of time open for current businesses
now = dt.datetime.now()

business_locs.loc[business_locs['Location End Date'].isnull(), 'Years Open'] = ((
    now - business_locs['Location Start Date']).dt.days)/365

In [96]:
business_locs.head()

,Location Id,Business Account Number,DBA Name,Street Address,Source Zipcode,Business Start Date,Business End Date,Location Start Date,Location End Date,Currently Open,Years Open
61,0000671-01-001,671,Aliotos,360 Jefferson St,94133,1968-10-01,NaT,1968-10-01,NaT,1.0,50.6137
62,0000671-01-002,671,Aliotos,8 Fisherman's Wharf,94133,1968-10-01,NaT,1968-10-01,NaT,1.0,50.6137
63,0000671-08-001,671,Nonna Rose Restaurant Inc,8 Fisherman's Wharf,94133,1968-10-01,NaT,2008-04-28,NaT,1.0,11.0137
64,0000671-09-001,671,Afc Cafe 8 Inc,8 Fisherman's Wharf,94133,1968-10-01,NaT,2008-04-28,NaT,1.0,11.0137
65,0000671-10-001,671,Afc Crabstand Inc,8 Fisherman's Wharf,94133,1968-10-01,NaT,2008-04-28,NaT,1.0,11.0137

In [101]:
#Pull New Restaurants out from table (currently open, and open < 2 years)
new_restaurants = business_locs.loc[(business_locs['Currently Open'] == 1) & (business_locs['Years Open'] < 2)]

In [104]:
#Closed Restaurants. Add column for 'Success' --> closed after being open longer than 2 years
#Remove closed restaurants that never opened (Years open <= 0) 
closed_restaurants = business_locs.loc[(business_locs['Currently Open'] == 0) & (business_locs['Years Open'] > 0)]

In [105]:
closed_restaurants

,Location Id,Business Account Number,DBA Name,Street Address,Source Zipcode,Business Start Date,Business End Date,Location Start Date,Location End Date,Currently Open,Years Open
281,0004965-02-001,4965,Sb40,40 Pier The Embarcadero,94107,1968-10-01,2017-04-30,2011-02-22,2017-04-30,0.0,6.18904
282,0004965-03-001,4965,Sb40/carmens,40 Pier The Embarcadero,94107,1968-10-01,2017-04-30,2012-03-22,2017-04-30,0.0,5.10959
1020,0015460-02-001,15460,Kentucky Fried Chicken,1900 Irving St,94122,1968-10-01,2016-09-28,1968-10-01,2016-09-28,0.0,48.0247
1427,0022850-01-001,22850,Pompeis Grotto,340 Jefferson St,94133,1968-10-01,2015-06-30,1968-10-01,2015-06-30,0.0,46.7753
1527,0024815-01-001,24815,Sams,618 Broadway St,94133,1968-10-01,2016-06-13,1968-10-01,2016-06-13,0.0,47.7315
1757,0028046-01-001,28046,Tarantinos Inc,206 Jefferson St,94133,1968-10-01,2018-01-25,1968-10-01,2018-01-25,0.0,49.3507
1825,0029436-01-001,29436,Uptons Catering,2435 Lombard St,94123,1968-10-01,NaT,1968-10-01,2014-06-29,0.0,45.7726
1838,0029798-01-001,29798,Victoria Pastry Co,1362 Stockton St,94133,1968-10-01,NaT,1968-10-01,2012-05-31,0.0,43.6932
3035,0038965-01-001,38965,3300 Club,3300 Mission St,94110,1968-10-01,2016-06-18,1968-10-01,2016-06-18,0.0,47.7452
3707,0046324-01-001,46324,Compass Group Usa Inc,200 Mcallister St,94102,1968-10-01,NaT,1968-10-01,1991-12-31,0.0,23.263
3708,0046324-05-001,46324,Eurest Dining-Virgin Atlantic,100 Upper Intl 1.5.113 Sfo,94128,1968-10-01,NaT,2004-01-01,2015-10-08,0.0,11.7753
3711,0046324-09-001,46324,Chartwells-Sf State,801 Font Blvd,94132,1968-10-01,NaT,2004-01-01,2015-07-15,0.0,11.5425
3714,0046324-16-001,46324,Eurest Dining Services,101 Market St,94105,1968-10-01,NaT,2011-01-01,2014-09-30,0.0,3.74795
3724,0046324-26-001,46324,Osullivan Vending Services,101 Market St,94105,1968-10-01,NaT,2013-12-16,2016-06-01,0.0,2.46027
3876,0048140-01-001,48140,Specs,12 William Saroyan Pl,94133,1968-10-01,NaT,1968-10-01,2017-02-01,0.0,48.3699
3994,0049670-01-001,49670,Lion Pub The,2062 Divisadero St,94115,1969-07-01,2016-09-11,1969-07-01,2016-09-11,0.0,47.2301
4031,0049983-01-001,49983,Pete's Deli,1661 Divisadero St,94115,1969-02-24,NaT,1969-02-24,2017-03-21,0.0,48.1014
4182,0051805-01-001,51805,Kentucky Fried Chicken,2101 Lombard St,94123,1968-10-01,2016-01-23,1968-10-01,2016-01-23,0.0,47.3425
4457,0055730-03-001,55730,Simple Espresso,1133 1/2 Shotwell St,94110,2002-04-15,NaT,2002-04-15,2002-08-31,0.0,0.378082
4499,0056107-25-001,56107,Orrick,405 Howard St,94105,2012-12-31,NaT,2012-12-31,2014-04-03,0.0,1.25479
4500,0056107-26-001,56107,Orrick Ocs,405 Howard St,94105,2012-12-31,NaT,2012-12-31,2014-04-03,0.0,1.25479
4508,0056107-44-001,56107,Dolby Cafe,999 Brannan St,94103,2012-12-31,NaT,2012-12-31,2015-04-30,0.0,2.32877
4594,0056952-01-001,56952,Pendulum Inc,4146 18th St,94114,1970-01-01,NaT,1970-01-01,2008-06-01,0.0,38.4411
4935,0061822-01-001,61822,Kentucky Fried Chicken,1881 Geary Blvd,94115,1968-11-02,2016-01-16,1968-11-02,2016-01-16,0.0,47.2356
6155,0078507-01-001,78507,Liverpool Lils Restaurant,2942 Lyon St,94123,1973-09-04,2018-05-29,1973-09-04,2018-05-29,0.0,44.7616
6549,0084298-01-001,84298,Pac Cafe,7000 Geary Blvd,94121,1974-07-04,2017-12-31,1974-07-04,2017-12-31,0.0,43.5233
6670,0087062-01-001,87062,Hunan Restaurant,924 Sansome St,94111,1974-02-01,2017-05-12,1974-02-01,2017-05-12,0.0,43.3041
6671,0087062-01-002,87062,Hunan Restaurant,1016 Bryant St,94103,1974-02-01,2017-05-12,1974-02-01,2007-12-31,0.0,33.9342
7411,0098407-01-001,98407,Fukuzushi,1581 Webster St,94115,2013-12-31,2016-09-06,1976-04-15,2014-05-19,0.0,38.1178
7412,0098407-02-001,98407,Sapporo-Ya,1581 Webster St,94115,2013-12-31,2016-09-06,2014-05-20,2016-06-06,0.0,2.04932
...,...,...,...,...,...,...,...,...,...,...,...
229814,1207375-12-181,1031762,Tacos Los Trinos,4384 Mission St,94112,2016-04-28,NaT,2018-12-11,2018-12-14,0.0,0.00821918
229915,1207545-12-181,1095903,Third Space Llc,647 Valencia St,94110,2018-12-13,2019-01-29,2018-12-13,2019-01-29,0.0,0.128767
230113,1207884-12-181,476913,April Fresh,4007 24th St,94114,2013-03-16,NaT,2018-12-18,2019-01-25,0.0,0.10411
230259,1208129-12-181,1096155,Nan King Road Bistro,1360 9th Ave,94122,2018-12-21,NaT,2018-12-21,2019-01-29,0.0,0.106849
230656,1208789-01-191,1096446,"Sarah's Latin Taste, Llc",36 Elm St,94070,2019-01-03,2019-01-04,2019-01-03,2019-01-04,0.0,0.00273973
230826,1209091-01-191,1096584,Kitchen Concept Llc,777 Figueroa St Ste 4100,90017,2019-01-07,NaT,2019-01-07,2019-03-01,0.0,0.145205
231445,1210089-01-191,1097031,Lavash,511 Irving Street,94122,2015-03-20,2019-01-16,2015-03-20,2019-01-16,0.0,3.83014
231456,1210111-01-191,1097044,Saltry Snacks,2125 Bryant St Unit 319,94110,2019-01-16,2019-01-16,2019-01-16,2019-02-01,0.0,0.0438356
231537,1210246-01-191,1097099,Tbd,925 Bush St,94109,2018-02-14,NaT,2019-01-17,2019-03-13,0.0,0.150685
231766,1210631-01-191,1096006,Stonestown Certified Farmers Market,3251 20th Ave,94132,2018-12-17,NaT,2019-01-23,2019-01-24,0.0,0.00273973
232060,1211119-01-191,1097480,Grem's Good Dog,S Van Ness Ave,94103,2019-01-28,NaT,2019-01-28,2019-01-29,0.0,0.00273973
232118,1211210-01-191,1031823,Hahdough,1080 Howard St,94103,2016-04-29,NaT,2019-01-28,2019-02-01,0.0,0.0109589
232183,1211325-01-191,1092701,Zorokuyuzan,125 Ellis St,94102,2018-09-12,NaT,2019-01-29,2019-04-10,0.0,0.194521
232315,1211553-01-191,149795,Gaspare's Pizza House & Italian Restaurant,5546 Geary Blvd,94121,1985-02-06,NaT,1985-02-06,2019-02-01,0.0,34.0082
232322,1211566-01-191,1097686,California's Gold,6748 Mission St Unit 410,94014,2019-01-31,NaT,2019-01-31,2019-02-01,0.0,0.00273973
232684,1212164-02-191,203860,Katana-Ya (Usa) Corporation,422 Geary St,94102,1991-03-25,NaT,2019-02-06,2019-03-01,0.0,0.0630137
233072,1212794-02-191,1098211,Sweets4treats,350 River Oaks Pkwy 1424,95134,2019-02-12,2019-03-06,2019-02-12,2019-03-06,0.0,0.060274
233169,1212969-02-191,1098291,Oh My Green@git Hub 3rd Floor,88 Collins P Kelley Jr. Rd,94107,2019-02-14,2019-02-14,2019-02-14,2019-03-28,0.0,0.115068
233472,1213506-02-191,1063433,Restaurante Hondureno Antojitos Pespire,5300 Mission St,94112,2017-01-06,NaT,2019-01-04,2019-03-14,0.0,0.189041
233787,1214050-02-191,1098781,Twirl And Dip,38 Teddy Ave,94134,2018-12-19,2019-03-19,2019-02-25,2019-03-19,0.0,0.060274
234220,1214779-03-191,1099085,Heroic Deli Sf,360 Corbett Ave,94114,2019-03-01,NaT,2019-03-01,2019-03-04,0.0,0.00821918
234274,1214851-03-191,1002064,Binis Kitchen Llc,1001 Howard St,94103,2014-03-01,NaT,2019-02-28,2019-04-08,0.0,0.106849
234485,1215198-03-191,1097879,Divisadero Cfm,1322 Grove St,94016,2019-02-05,NaT,2019-03-05,2019-03-13,0.0,0.0219178
234629,1215442-03-191,1099352,Eclectic Cookery,103 Horne Ave,94010,2019-03-07,NaT,2019-03-07,2019-03-21,0.0,0.0383562
235420,1216703-03-191,1099878,Edwin Ng,2001 Union St Ste 107,94123,2019-03-21,NaT,2019-03-21,2019-03-22,0.0,0.00273973
235433,1216727-03-191,1099890,Lamas Peruvian Food Llc,268 Hillside Blvd,94014,2019-03-18,NaT,2019-03-18,2019-03-26,0.0,0.0219178
235464,1216788-03-191,1099922,Kaiser Geary Farmers Market,2425 Geary Blvd,95616,2019-03-22,NaT,2019-03-22,2019-04-03,0.0,0.0328767
235484,1216809-03-191,1099902,King Of Thai Noodle House,1810 O'farrel St,94102,2019-03-22,NaT,2019-03-22,2019-03-25,0.0,0.00821918
235690,1217134-03-191,1100055,Tassili Food,32 6th St,94103,2019-01-01,NaT,2019-01-01,2019-04-04,0.0,0.254795
236052,1217707-04-191,1098850,Inovino,108 Carl St B,94117,2018-02-24,NaT,2018-04-24,2019-04-09,0.0,0.958904

In [ ]:
#Successful --> Stayed open longer than 2 years

In [ ]:
#Remove observations for restaurants that are currently open but have only been open <2 years 
#(Can't determine for certain if they are 'successful', since they haven't been open for 
# two years yet -- they're like 'not failures yet')